# mesmis interactivo
load_mesmis_interactivo:
  url: /mi/mesmis-interactivo
  param: { module: product, action: loadMI}

open_mesmis_interactivo:
  url: /mesmis-interactivo
  param: { module: product, action: openMI}

mesmis_interactivo:
  url: /mesmis-interactivo
  param: { module: product, action: openMI, sf_culture: es}
  
mesmis_interactive:
  url: /mesmis-interactive
  param: { module: product, action: openMI, sf_culture: en}

# homepages
homepage:
  url:   /
  param: { module: news, action: index }

hompage_culture:
  url:   /:sf_culture
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: index }

# news module
news_item_read:
  url: /:sf_culture/news/read/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: view }

news_items_list:
  url: /:sf_culture/news
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: index }

# product module
poduct_action:
  url: /:sf_culture/product/:action/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: product}

poduct_action:
  url: /:sf_culture/products/:action/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: product}

products_list:
  url: /:sf_culture/products
  requirements: { sf_culture: (?:es|en) }
  param: { module: product, action: index }

# content module
content:
  url:   /:sf_culture/content/:alias
  requirements: { sf_culture: (?:es|en) }
  param: { module: content, action: index }

# static module
static:
  url:   /:sf_culture/static/:content
  requirements: { sf_culture: (?:es|en) }
  param: { module: static, action: index }

# comment module
comment:
  url:   /:sf_culture/comment/:action
  requirements: { sf_culture: (?:es|en) }
  param: { module: comment}

# generic modules
default_index:
  url:   /:sf_culture/:module
  requirements: { sf_culture: (?:es|en) }
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
  requirements: { sf_culture: (?:es|en) }
