news_item_read:
  url: /:sf_culture/news/read/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: view }

news_items_list:
  url: /:sf_culture/news
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: index }

poduct_action:
  url: /:sf_culture/products/:action/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: product}

products_list:
  url: /:sf_culture/products
  requirements: { sf_culture: (?:es|en) }
  param: { module: product, action: index }

content:
  url:   /:sf_culture/content/:alias
  requirements: { sf_culture: (?:es|en) }
  param: { module: content, action: index }

static:
  url:   /:sf_culture/static/:content
  requirements: { sf_culture: (?:es|en) }
  param: { module: static, action: index }

# default rules
homepage:
  url:   /
  param: { module: news, action: index }

hompage_culture:
  url:   /:culture
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: index }

default_index:
  url:   /:culture/:module
  requirements: { sf_culture: (?:es|en) }
  param: { action: index }

default:
  url:   /:culture/:module/:action/*
  requirements: { sf_culture: (?:es|en) }
