# mesmis interactivo
mesmis_interactivo:
  url: /mesmis-interactivo
  param: { module: product, action: open, id: 16, sf_culture: es}

# homepages
homepage:
  url:   /
  param: { module: news, action: index }

hompage_culture:
  url:   /:sf_culture
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: index }

# news module
news_item_read:
  url: /:sf_culture/news/read/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: view }

news_items_list:
  url: /:sf_culture/news
  requirements: { sf_culture: (?:es|en) }
  param: { module: news, action: index }

# product module
poduct_action:
  url: /:sf_culture/products/:action/:id
  requirements: { sf_culture: (?:es|en) }
  param: { module: product}

products_list:
  url: /:sf_culture/products
  requirements: { sf_culture: (?:es|en) }
  param: { module: product, action: index }

# content module
content:
  url:   /:sf_culture/content/:alias
  requirements: { sf_culture: (?:es|en) }
  param: { module: content, action: index }

# static module
static:
  url:   /:sf_culture/static/:content
  requirements: { sf_culture: (?:es|en) }
  param: { module: static, action: index }

# generic modules
default_index:
  url:   /:culture/:module
  requirements: { sf_culture: (?:es|en) }
  param: { action: index }

default:
  url:   /:culture/:module/:action/*
  requirements: { sf_culture: (?:es|en) }
