content:
  url:   /content/:alias
  param: { module: content, action: index }

static:
  url:   /static/:content
  param: { module: static, action: index }

# default rules
homepage:
  url:   /
  param: { module: news, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
