default:
  http_metas:
    content-type: text/html

  metas:
    title:        MESMIS
    description:  Marco para la Evaluación de Sistemas de Manejo de recursos naturales incorporando Indicadores de Sustentabilidad
    keywords:     mesmis evaluación sistemas manejo indicadores sustentabilidad
    language:     es
    robots:       index, follow

  stylesheets:    [main-frontend.css]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, frontend]

  has_layout:     on
  layout:         layout
