default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main-frontend.css]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, frontend]

  has_layout:     on
  layout:         layout
