#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          mysql://root@localhost/dbname
dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      phptype: mysql
      dsn: 'mysql:host=localhost;dbname=mesmisweb'
      database: mesmisweb
      username: usrmesmis
      password: usrmesmis
      encoding: utf8
      persistent: true
      pooling: true
