propel:
  user:
    id:              ~
    name:            { type: varchar(50), required: true }
    surname1:        { type: varchar(50), required: true }
    surname2:        { type: varchar(50) }
    email:           { type: varchar(255), required: true }
    institution:     { type: varchar(255) }
    created_at:      ~
    updated_at:      ~
  visit:
    user_id:         ~
    ip:              { type: varchar(15) }
    created_at:      ~
  comment:
    user_id:         ~
    comment:         { type: longvarchar }
    created_at:      ~
  content:
    _attributes:     { phpName: Content }
    id:              ~
    alias:           { type: varchar(50) }
    state:           { type: varchar(10), default: PUBLISHED }
    created_at:      ~
    updated_at:      ~
  content_i18n:
    _attributes:     { phpName: ContentI18n }
    title:           { type: longvarchar, required: true }
    body:            { type: longvarchar }
  news_item:
    _attributes:     { phpName: NewsItem }
    id:              ~
    photo_filename:  { type: varchar(255) }
    priority:        { type: integer }
    state:           { type: varchar(10), default: PUBLISHED }
    created_at:      ~
    updated_at:      ~
  news_item_i18n:
    _attributes:     { phpName: NewsItemI18n }
    title:           { type: varchar(255), required: true }
    body:            { type: longvarchar }
  product_group:
    _attributes:     { phpName: ProductGroup }
    id:              ~
    alias:           { type: varchar(20) }
  product_group_i18n:
    _attributes:     { phpName: ProductGroupI18n }
    title:           { type: varchar(255), required: true }
  product:
    _attributes:     { phpName: Product }
    id:              ~
    product_group_id: ~
    mimetype:        { type: varchar(20) }
    priority:        { type: integer }
    type:            { type: varchar(10) }
    state:           { type: varchar(10), default: PUBLISHED }
    created_at:      ~
    updated_at:      ~
  product_i18n:
    _attributes:     { phpName: ProductI18n }
    title:           { type: varchar(255), required: true }
    descrip:         { type: longvarchar }
    resource:        { type: varchar(255) }
  download:
    user_id:         ~
    product_id:      ~
    culture:         { isCulture: true, type: varchar(7), required: true }
    created_at:      ~
    
